### ISSUE TITLE
WebDriverException message is empty during session creation

### ISSUE THREAD

**Issue by bmarroquin** [FlaUI/FlaUI.WebDriver#86]
```
Traceback (most recent call last):
  File "...\__init__.py", line 38, in create_driver_by_exe_name
    return webdriver.Remote(self.url, options=AppiumOptions().load_capabilities(caps))
  File "...\.venv\lib\site-packages\appium\webdriver\webdriver.py", line 229, in __init__
    super().__init__(
  File "...\.venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 212, in __init__
    self.start_session(capabilities)
  File "...\.venv\lib\site-packages\appium\webdriver\webdriver.py", line 319, in start_session
    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)
  File "...\.venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "...\.venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 193, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message: 
```

**Comment by aristotelos** [comment]
Are there any errors in the output logging of FlaUI.WebDriver? To collect debug logs run with `\FlaUI.WebDriver.exe --Logging:LogLevel:Default=Debug`. Could you share the output here?

**Comment by bmarroquin** [comment]
I'm away from the computer that has the log, will upload on Monday. If i remember correctly, the log has an error of failing to find a process id while trying to attach to the application. The App we use has some weird launcher logic and i think that is at fault, but it would be good to see the error from the client.

There might be a need for an ExceptionHandler middleware to handle uncaught exceptions and transform them to something the appium clients can see.
